# Generated by Django 5.1.7 on 2025-06-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('subjects_interest', models.JSONField(default=list)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('goals', models.TextField(blank=True)),
                ('preferred_languages', models.JSONField(default=list)),
                ('time_slots', models.JSONField(default=list)),
                ('learning_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'In-person'), ('hybrid', 'Hybrid')], max_length=20)),
                ('learning_history', models.JSONField(default=list)),
                ('bookmarks', models.JSONField(default=list)),
                ('payment_methods', models.JSONField(default=list)),
                ('reviews_given', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('subjects', models.JSONField(default=list)),
                ('grade_levels', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('experience', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('availability', models.JSONField(default=dict)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'In-person'), ('hybrid', 'Hybrid')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
