# Generated by Django 5.1.7 on 2025-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bookmarks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'In-person'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reviews_given',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects_interest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'In-person'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
