# Generated by Django 5.1.7 on 2025-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_studentprofile_bookmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='mode',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='booking_deadline',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum minutes before session start to book.', null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='cancellation_policy',
            field=models.CharField(blank=True, choices=[('12hr', 'Up to 12 hrs before'), ('24hr', 'Up to 24 hrs before'), ('non-refundable', 'Non-refundable')], max_length=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='instant_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='materials_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_students',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade_levels',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.TextField(blank=True, help_text='Comma-separated subjects'),
        ),
    ]
