# Generated by Django 5.1.7 on 2025-07-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='jitsi_meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
