# Generated by Django 5.1.7 on 2025-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='booking_deadline_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='availability',
            name='cancellation_policy',
            field=models.CharField(choices=[('24hr', 'Cancel before 24 hours'), ('12hr', 'Cancel before 12 hours'), ('none', 'No cancellation after booking')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='grade_level',
            field=models.CharField(choices=[('Grade 10', 'Grade 10'), ('11-12', 'Class 11-12'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='instant_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Bilingual', 'Bilingual')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='materials_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='max_students',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='platform',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('MS Teams', 'MS Teams'), ('Skype', 'Skype'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('per_hour', 'Per Hour'), ('per_booking', 'Per Booking')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='repeat_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='session_type',
            field=models.CharField(choices=[('1v1', 'One-on-One'), ('group', 'Group')], default='1v1', max_length=10),
        ),
        migrations.AddField(
            model_name='availability',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
