# Generated by Django 5.1.7 on 2025-07-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tutoringsession_jitsi_meeting_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutoringsession',
            old_name='jitsi_meeting_url',
            new_name='jitsi_link',
        ),
    ]
