# Generated by Django 5.1.7 on 2025-06-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_availability_booking_deadline_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='repeat_days',
        ),
        migrations.AddField(
            model_name='availability',
            name='repeat_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='booking_deadline_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='cancellation_policy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='availability',
            name='grade_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='max_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='availability',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('per_hour', 'Per Hour'), ('per_booking', 'Per Booking')], default='per_booking', max_length=50),
        ),
        migrations.AlterField(
            model_name='availability',
            name='session_type',
            field=models.CharField(choices=[('1v1', '1-on-1'), ('group', 'Group')], default='1v1', max_length=20),
        ),
        migrations.AlterField(
            model_name='availability',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
