# Generated by Django 5.1.7 on 2025-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_availability_repeat_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='instant_booking',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='subject',
        ),
        migrations.AlterField(
            model_name='availability',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('1-5', 'Grade 1-5'), ('6-10', 'Grade 6-10'), ('11-12', 'Grade 11-12'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=50),
        ),
        migrations.AddField(
            model_name='availability',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='bookings.subject'),
        ),
    ]
