# Generated by Django 5.1.7 on 2025-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_subject_remove_availability_instant_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10, null=True),
        ),
    ]
